
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int CommentId { get; set; }

    public int PresentationId { get; set; }

    public int UsesrId { get; set; }

    public string UserName { get; set; }

    public string Time { get; set; }

    public string Content { get; set; }

    public bool IsPrivate { get; set; }

    public bool IsAnonymous { get; set; }

}

}
