

//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EchoDBEntities : DbContext
{
    public EchoDBEntities()
        : base("name=EchoDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Presentation> Presentations { get; set; }

    public DbSet<UpVote> UpVotes { get; set; }

    public DbSet<Comment> Comments { get; set; }

    public DbSet<FREECOMMENT> FREECOMMENTs { get; set; }

    public DbSet<FREEUSERNAME> FREEUSERNAMEs { get; set; }

    public DbSet<FREEVOTE> FREEVOTEs { get; set; }

    public DbSet<RateVideo> RateVideos { get; set; }

    public DbSet<WatchedPresentation> WatchedPresentations { get; set; }

    public DbSet<WoGamCategory> WoGamCategories { get; set; }

    public DbSet<WoGamProfile> WoGamProfiles { get; set; }

    public DbSet<WoGamWord> WoGamWords { get; set; }

    public DbSet<UserProfile> UserProfiles { get; set; }

    public DbSet<webpages_Membership> webpages_Membership { get; set; }

    public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }

    public DbSet<webpages_Roles> webpages_Roles { get; set; }

}

}

