//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateVideo
    {
        public int Id { get; set; }
        public int PresentationId { get; set; }
        public int UserId { get; set; }
        public int Rate { get; set; }
        public int VideoCreatorId { get; set; }
    }
}
