
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RateVideo
{

    public int Id { get; set; }

    public int PresentationId { get; set; }

    public int UserId { get; set; }

    public int Rate { get; set; }

    public int VideoCreatorId { get; set; }

}

}
