
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class webpages_Roles
{

    public webpages_Roles()
    {

        this.UserProfiles = new HashSet<UserProfile>();

    }


    public int RoleId { get; set; }

    public string RoleName { get; set; }



    public virtual ICollection<UserProfile> UserProfiles { get; set; }

}

}
