
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WoGamCategory
{

    public WoGamCategory()
    {

        this.WoGamWords = new HashSet<WoGamWord>();

    }


    public int cat_id { get; set; }

    public string cat_name { get; set; }

    public bool cat_reached { get; set; }

    public string cat_url { get; set; }

    public int cat_usr { get; set; }

    public string cat_langage { get; set; }



    public virtual ICollection<WoGamWord> WoGamWords { get; set; }

    public virtual WoGamProfile WoGamProfile { get; set; }

}

}
