
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WoGamChoice
{

    public int chc_id { get; set; }

    public int chc_usr { get; set; }

    public int chc_langage { get; set; }



    public virtual WoGamProfile WoGamProfile { get; set; }

    public virtual WoGamLangage WoGamLangage { get; set; }

}

}
