
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WoGamWord
{

    public int wd_id { get; set; }

    public string wd_value { get; set; }

    public int wd_nbtime { get; set; }

    public int wd_cat { get; set; }

    public string wd_url { get; set; }



    public virtual WoGamCategory WoGamCategory { get; set; }

}

}
