//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoGamLangage
    {
        public WoGamLangage()
        {
            this.WoGamCategories = new HashSet<WoGamCategory>();
            this.WoGamChoices = new HashSet<WoGamChoice>();
        }
    
        public int lng_id { get; set; }
        public string lng_langage { get; set; }
    
        public virtual ICollection<WoGamCategory> WoGamCategories { get; set; }
        public virtual ICollection<WoGamChoice> WoGamChoices { get; set; }
    }
}
