
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EchoMe.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WoGamLangage
{

    public WoGamLangage()
    {

        this.WoGamCategories = new HashSet<WoGamCategory>();

        this.WoGamChoices = new HashSet<WoGamChoice>();

    }


    public int lng_id { get; set; }

    public string lng_langage { get; set; }



    public virtual ICollection<WoGamCategory> WoGamCategories { get; set; }

    public virtual ICollection<WoGamChoice> WoGamChoices { get; set; }

}

}
