//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoGamProfile
    {
        public WoGamProfile()
        {
            this.WoGamChoices = new HashSet<WoGamChoice>();
        }
    
        public int usr_id { get; set; }
        public string usr_name { get; set; }
        public string usr_pwd { get; set; }
        public string usr_gameLangage { get; set; }
    
        public virtual ICollection<WoGamChoice> WoGamChoices { get; set; }
    }
}
