//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoGamWord
    {
        public int wd_id { get; set; }
        public string wd_value { get; set; }
        public int wd_nbtime { get; set; }
        public int wd_cat { get; set; }
    
        public virtual WoGamCategory WoGamCategory { get; set; }
    }
}
