//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoGamChoice
    {
        public int chc_id { get; set; }
        public int chc_usr { get; set; }
        public int chc_langage { get; set; }
    
        public virtual WoGamProfile WoGamProfile { get; set; }
        public virtual WoGamLangage WoGamLangage { get; set; }
    }
}
